
#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ def in_list(key, list):
#@  return hasattr(data.values.tap_values, key) and (data.values.tap_values[key] in list)
#@ end
#@ if/end in_list('supply_chain', ['testing_scanning']) and in_list('profile', ['full', 'build']):
---
apiVersion: v1
kind: Secret
metadata:
  name: carbonblack-token-secret
stringData:
  cbc_api_id: #@ base64.encode(data.values.imported.scanners.cbc_api_id) if hasattr(data.values, "imported") and hasattr(data.values.imported, "scanners") and hasattr(data.values.imported.scanners, "cbc_api_id") else ""
  cbc_api_key: #@ base64.encode(data.values.imported.scanners.cbc_api_key) if hasattr(data.values, "imported") and hasattr(data.values.imported, "scanners") and hasattr(data.values.imported.scanners, "cbc_api_key") else ""
  cbc_org_key: #@ base64.encode(data.values.imported.scanners.cbc_org_key) if hasattr(data.values, "imported") and hasattr(data.values.imported, "scanners") and hasattr(data.values.imported.scanners, "cbc_org_key") else ""
  cbc_saas_url: #@ base64.encode(data.values.imported.scanners.cbc_saas_url) if hasattr(data.values, "imported") and hasattr(data.values.imported, "scanners") and hasattr(data.values.imported.scanners, "cbc_saas_url") else ""